services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: inventoryuser
      POSTGRES_PASSWORD: inventorypassword
      POSTGRES_DB: inventorydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
