# Generated by Django 4.2.15 on 2024-08-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='inventory',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sale',
        ),
        migrations.AlterModelTable(
            name='warehouse',
            table='warehouse',
        ),
    ]
